
time="2025-07-27T02:44:29-03:00" level=warning msg="/home/rinha-user/rinha-de-backend-2025/participantes/Maxel-Uds-quarkus/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
 Network maxel-uds-quarkus_payment-router  Creating
 Network maxel-uds-quarkus_payment-router  Created
 Container postgres  Creating
 Container postgres  Created
 Container api2  Creating
 Container api1  Creating
 Container api1  Created
 Container api2  Created
 Container load_balancer  Creating
 Container load_balancer  Created
Attaching to api1, api2, load_balancer, postgres
postgres       | The files belonging to this database system will be owned by user "postgres".
postgres       | This user must also own the server process.
postgres       | 
postgres       | The database cluster will be initialized with locale "en_US.utf8".
postgres       | The default database encoding has accordingly been set to "UTF8".
postgres       | The default text search configuration will be set to "english".
postgres       | 
postgres       | Data page checksums are disabled.
postgres       | 
postgres       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres       | creating subdirectories ... ok
postgres       | selecting dynamic shared memory implementation ... posix
postgres       | selecting default max_connections ... 100
postgres       | selecting default shared_buffers ... 128MB
postgres       | selecting default time zone ... Etc/UTC
postgres       | creating configuration files ... ok
postgres       | running bootstrap script ... ok
postgres       | performing post-bootstrap initialization ... ok
postgres       | syncing data to disk ... ok
postgres       | 
postgres       | 
postgres       | Success. You can now start the database server using:
postgres       | 
postgres       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres       | 
postgres       | initdb: warning: enabling "trust" authentication for local connections
postgres       | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
postgres       | waiting for server to start....2025-07-27 05:44:36.281 UTC [50] LOG:  starting PostgreSQL 16.9 (Debian 16.9-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres       | 2025-07-27 05:44:36.286 UTC [50] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres       | 2025-07-27 05:44:36.308 UTC [53] LOG:  database system was shut down at 2025-07-27 05:44:35 UTC
postgres       | 2025-07-27 05:44:36.316 UTC [50] LOG:  database system is ready to accept connections
postgres       |  done
postgres       | server started
postgres       | CREATE DATABASE
postgres       | 
postgres       | 
postgres       | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
postgres       | psql:/docker-entrypoint-initdb.d/init.sql:1: NOTICE:  table "payments" does not exist, skipping
postgres       | DROP TABLE
postgres       | CREATE TABLE
postgres       | 
postgres       | 
postgres       | waiting for server to shut down...2025-07-27 05:44:37.117 UTC [50] LOG:  received fast shutdown request
postgres       | .2025-07-27 05:44:37.133 UTC [50] LOG:  aborting any active transactions
postgres       | 2025-07-27 05:44:37.183 UTC [50] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
postgres       | 2025-07-27 05:44:37.184 UTC [51] LOG:  shutting down
postgres       | 2025-07-27 05:44:37.191 UTC [51] LOG:  checkpoint starting: shutdown immediate
postgres       | 2025-07-27 05:44:37.304 UTC [51] LOG:  checkpoint complete: wrote 922 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.025 s, sync=0.072 s, total=0.121 s; sync files=303, longest=0.038 s, average=0.001 s; distance=4263 kB, estimate=4263 kB; lsn=0/19140B0, redo lsn=0/19140B0
postgres       | 2025-07-27 05:44:37.311 UTC [50] LOG:  database system is shut down
postgres       |  done
postgres       | server stopped
postgres       | 
postgres       | PostgreSQL init process complete; ready for start up.
postgres       | 
postgres       | 2025-07-27 05:44:37.408 UTC [1] LOG:  starting PostgreSQL 16.9 (Debian 16.9-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres       | 2025-07-27 05:44:37.408 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres       | 2025-07-27 05:44:37.408 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres       | 2025-07-27 05:44:37.426 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres       | 2025-07-27 05:44:37.443 UTC [68] LOG:  database system was shut down at 2025-07-27 05:44:37 UTC
postgres       | 2025-07-27 05:44:37.481 UTC [1] LOG:  database system is ready to accept connections
api2           | __  ____  __  _____   ___  __ ____  ______ 
api2           |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api2           |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api2           | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api2           | 2025-07-27 05:44:38,494 INFO  [io.quarkus] (main) payment-router 1.0.0-SNAPSHOT native (powered by Quarkus 3.11.1) started in 0.106s. Listening on: http://0.0.0.0:8080
api2           | 2025-07-27 05:44:38,494 INFO  [io.quarkus] (main) Profile prod activated. 
api2           | 2025-07-27 05:44:38,494 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, narayana-jta, rest, rest-client, rest-client-jackson, rest-jackson, smallrye-context-propagation, vertx]
api1           | __  ____  __  _____   ___  __ ____  ______ 
api1           |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api1           |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api1           | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api1           | 2025-07-27 05:44:38,497 INFO  [io.quarkus] (main) payment-router 1.0.0-SNAPSHOT native (powered by Quarkus 3.11.1) started in 0.109s. Listening on: http://0.0.0.0:8080
api1           | 2025-07-27 05:44:38,497 INFO  [io.quarkus] (main) Profile prod activated. 
api1           | 2025-07-27 05:44:38,497 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, narayana-jta, rest, rest-client, rest-client-jackson, rest-jackson, smallrye-context-propagation, vertx]
load_balancer  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
load_balancer  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
load_balancer  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
load_balancer  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
load_balancer  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
load_balancer  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
load_balancer  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
load_balancer  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
load_balancer  | /docker-entrypoint.sh: Configuration complete; ready for start up
[Kload_balancer exited with code 0
api1           | 2025-07-27 05:45:52,979 INFO  [io.qua.thread-pool] (main) Awaiting thread pool shutdown; 15 thread(s) running with 0 task(s) waiting
api2           | 2025-07-27 05:45:52,990 INFO  [io.qua.thread-pool] (Shutdown thread) Awaiting thread pool shutdown; 15 thread(s) running with 0 task(s) waiting
api2           | 2025-07-27 05:45:57,991 ERROR [org.jbo.thr.errors] (executor-thread-6) Thread Thread[#44,executor-thread-6,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-27 05:45:57,991 ERROR [org.jbo.thr.errors] (executor-thread-7) Thread Thread[#45,executor-thread-7,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-27 05:45:57,991 ERROR [org.jbo.thr.errors] (executor-thread-5) Thread Thread[#43,executor-thread-5,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-27 05:45:57,991 ERROR [org.jbo.thr.errors] (executor-thread-8) Thread Thread[#46,executor-thread-8,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-27 05:45:57,991 ERROR [org.jbo.thr.errors] (executor-thread-2) Thread Thread[#40,executor-thread-2,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-27 05:45:57,991 ERROR [org.jbo.thr.errors] (executor-thread-9) Thread Thread[#47,executor-thread-9,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-27 05:45:57,991 ERROR [org.jbo.thr.errors] (executor-thread-12) Thread Thread[#50,executor-thread-12,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-27 05:45:57,991 INFO  [io.qua.thread-pool] (Shutdown thread) Awaiting thread pool shutdown; 9 thread(s) running with 0 task(s) waiting
api2           | 2025-07-27 05:45:57,993 ERROR [org.jbo.thr.errors] (executor-thread-3) Thread Thread[#41,executor-thread-3,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-27 05:45:57,991 ERROR [org.jbo.thr.errors] (executor-thread-11) Thread Thread[#49,executor-thread-11,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-27 05:45:57,991 ERROR [org.jbo.thr.errors] (executor-thread-13) Thread Thread[#51,executor-thread-13,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-27 05:45:57,993 ERROR [org.jbo.thr.errors] (executor-thread-14) Thread Thread[#52,executor-thread-14,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-27 05:45:57,993 ERROR [org.jbo.thr.errors] (executor-thread-1) Thread Thread[#39,executor-thread-1,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-27 05:45:57,993 ERROR [org.jbo.thr.errors] (executor-thread-4) Thread Thread[#42,executor-thread-4,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-27 05:45:57,993 ERROR [org.jbo.thr.errors] (executor-thread-15) Thread Thread[#53,executor-thread-15,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-27 05:45:57,993 ERROR [org.jbo.thr.errors] (executor-thread-10) Thread Thread[#48,executor-thread-10,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api2           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api2           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api2           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api2           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api2           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api2           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api2           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api2           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api2           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api2           | Caused by: java.lang.InterruptedException
api2           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api2           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api2           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api2           | 	... 13 more
api2           | 
api2           | 2025-07-27 05:45:57,994 INFO  [io.quarkus] (Shutdown thread) payment-router stopped in 10.026s
api1           | 2025-07-27 05:45:57,996 INFO  [io.qua.thread-pool] (main) Awaiting thread pool shutdown; 15 thread(s) running with 0 task(s) waiting
api1           | 2025-07-27 05:45:57,996 ERROR [org.jbo.thr.errors] (executor-thread-12) Thread Thread[#50,executor-thread-12,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-27 05:45:58,004 ERROR [org.jbo.thr.errors] (executor-thread-6) Thread Thread[#44,executor-thread-6,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-27 05:45:57,996 ERROR [org.jbo.thr.errors] (executor-thread-11) Thread Thread[#49,executor-thread-11,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-27 05:45:58,004 ERROR [org.jbo.thr.errors] (executor-thread-10) Thread Thread[#48,executor-thread-10,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-27 05:45:58,004 ERROR [org.jbo.thr.errors] (executor-thread-7) Thread Thread[#45,executor-thread-7,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-27 05:45:58,004 ERROR [org.jbo.thr.errors] (executor-thread-14) Thread Thread[#52,executor-thread-14,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-27 05:45:58,004 ERROR [org.jbo.thr.errors] (executor-thread-15) Thread Thread[#53,executor-thread-15,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-27 05:45:58,004 ERROR [org.jbo.thr.errors] (executor-thread-3) Thread Thread[#41,executor-thread-3,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-27 05:45:58,004 ERROR [org.jbo.thr.errors] (executor-thread-13) Thread Thread[#51,executor-thread-13,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-27 05:45:58,004 ERROR [org.jbo.thr.errors] (executor-thread-2) Thread Thread[#40,executor-thread-2,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-27 05:45:58,004 ERROR [org.jbo.thr.errors] (executor-thread-8) Thread Thread[#46,executor-thread-8,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-27 05:45:58,004 ERROR [org.jbo.thr.errors] (executor-thread-4) Thread Thread[#42,executor-thread-4,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-27 05:45:58,004 ERROR [org.jbo.thr.errors] (executor-thread-9) Thread Thread[#47,executor-thread-9,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-27 05:45:58,004 ERROR [org.jbo.thr.errors] (executor-thread-5) Thread Thread[#43,executor-thread-5,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-27 05:45:58,004 ERROR [org.jbo.thr.errors] (executor-thread-1) Thread Thread[#39,executor-thread-1,5,main] threw an uncaught exception [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.InterruptedException
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:40)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.lambda$onStart$0(PaymentProcessorWorker.java:33)
api1           | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
api1           | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:604)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
api1           | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
api1           | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
api1           | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
api1           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
api1           | 	at java.base@21.0.7/java.lang.Thread.runWith(Thread.java:1596)
api1           | 	at java.base@21.0.7/java.lang.Thread.run(Thread.java:1583)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
api1           | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
api1           | Caused by: java.lang.InterruptedException
api1           | 	at java.base@21.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1727)
api1           | 	at java.base@21.0.7/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
api1           | 	at org.payment.router.worker.PaymentProcessorWorker.getNextPayment(PaymentProcessorWorker.java:38)
api1           | 	... 13 more
api1           | 
api1           | 2025-07-27 05:45:58,006 INFO  [io.quarkus] (main) payment-router stopped in 10.038s
[Kapi2 exited with code 143
[Kapi1 exited with code 143
postgres       | 2025-07-27 05:45:58.778 UTC [1] LOG:  received fast shutdown request
postgres       | 2025-07-27 05:45:58.785 UTC [1] LOG:  aborting any active transactions
postgres       | 2025-07-27 05:45:58.787 UTC [1] LOG:  background worker "logical replication launcher" (PID 71) exited with exit code 1
postgres       | 2025-07-27 05:45:58.789 UTC [66] LOG:  shutting down
postgres       | 2025-07-27 05:45:58.798 UTC [66] LOG:  checkpoint starting: shutdown immediate
postgres       | 2025-07-27 05:45:58.913 UTC [66] LOG:  checkpoint complete: wrote 422 buffers (2.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.025 s, sync=0.069 s, total=0.124 s; sync files=24, longest=0.061 s, average=0.003 s; distance=4958 kB, estimate=4958 kB; lsn=0/1DEBB40, redo lsn=0/1DEBB40
postgres       | 2025-07-27 05:45:58.918 UTC [1] LOG:  database system is shut down
[Kpostgres exited with code 0
log truncated at line 1000
