
time="2025-08-01T08:05:46-03:00" level=warning msg="/home/rinha-user/rinha-de-backend-2025/participantes/franklaercio/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
 Network franklaercio_backend  Creating
 Network franklaercio_backend  Created
 Volume "franklaercio_postgres_data"  Creating
 Volume "franklaercio_postgres_data"  Created
 Volume "franklaercio_redis_data"  Creating
 Volume "franklaercio_redis_data"  Created
 Container db  Creating
 Container redis  Creating
 Container redis  Created
 Container db  Created
 Container franklaercio-api2-1  Creating
 Container franklaercio-api1-1  Creating
 Container franklaercio-api2-1  Created
 Container franklaercio-api1-1  Created
 Container nginx_load_balancer  Creating
 Container nginx_load_balancer  Created
Attaching to db, api1-1, api2-1, nginx_load_balancer, redis
redis                | 1:C 01 Aug 2025 11:05:47.799 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis                | 1:C 01 Aug 2025 11:05:47.799 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis                | 1:C 01 Aug 2025 11:05:47.799 * Redis version=7.4.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis                | 1:C 01 Aug 2025 11:05:47.799 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis                | 1:M 01 Aug 2025 11:05:47.799 * monotonic clock: POSIX clock_gettime
redis                | 1:M 01 Aug 2025 11:05:47.800 * Running mode=standalone, port=6379.
redis                | 1:M 01 Aug 2025 11:05:47.801 * Server initialized
redis                | 1:M 01 Aug 2025 11:05:47.801 * Ready to accept connections tcp
db                   | The files belonging to this database system will be owned by user "postgres".
db                   | This user must also own the server process.
db                   | 
db                   | The database cluster will be initialized with locale "en_US.utf8".
db                   | The default database encoding has accordingly been set to "UTF8".
db                   | The default text search configuration will be set to "english".
db                   | 
db                   | Data page checksums are disabled.
db                   | 
db                   | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db                   | creating subdirectories ... ok
db                   | selecting dynamic shared memory implementation ... posix
db                   | selecting default max_connections ... 100
db                   | selecting default shared_buffers ... 128MB
db                   | selecting default time zone ... UTC
db                   | creating configuration files ... ok
db                   | running bootstrap script ... ok
db                   | sh: locale: not found
db                   | 2025-08-01 11:05:49.209 UTC [36] WARNING:  no usable system locales were found
db                   | performing post-bootstrap initialization ... ok
db                   | syncing data to disk ... ok
db                   | 
db                   | 
db                   | Success. You can now start the database server using:
db                   | 
db                   |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db                   | 
db                   | initdb: warning: enabling "trust" authentication for local connections
db                   | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db                   | waiting for server to start....2025-08-01 11:05:50.814 UTC [48] LOG:  starting PostgreSQL 15.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
db                   | 2025-08-01 11:05:50.814 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db                   | 2025-08-01 11:05:50.816 UTC [51] LOG:  database system was shut down at 2025-08-01 11:05:50 UTC
db                   | 2025-08-01 11:05:50.819 UTC [48] LOG:  database system is ready to accept connections
db                   |  done
db                   | server started
db                   | CREATE DATABASE
db                   | 
db                   | 
db                   | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db                   | CREATE TABLE
db                   | CREATE INDEX
db                   | 
db                   | 
db                   | waiting for server to shut down...2025-08-01 11:05:51.023 UTC [48] LOG:  received fast shutdown request
db                   | .2025-08-01 11:05:51.023 UTC [48] LOG:  aborting any active transactions
db                   | 2025-08-01 11:05:51.102 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db                   | 2025-08-01 11:05:51.102 UTC [49] LOG:  shutting down
db                   | 2025-08-01 11:05:51.102 UTC [49] LOG:  checkpoint starting: shutdown immediate
db                   | 2025-08-01 11:05:51.109 UTC [49] LOG:  checkpoint complete: wrote 928 buffers (18.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.001 s, total=0.008 s; sync files=0, longest=0.000 s, average=0.000 s; distance=4262 kB, estimate=4262 kB
db                   | 2025-08-01 11:05:51.117 UTC [48] LOG:  database system is shut down
db                   |  done
db                   | server stopped
db                   | 
db                   | PostgreSQL init process complete; ready for start up.
db                   | 
db                   | 2025-08-01 11:05:51.145 UTC [1] LOG:  starting PostgreSQL 15.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
db                   | 2025-08-01 11:05:51.145 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db                   | 2025-08-01 11:05:51.145 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db                   | 2025-08-01 11:05:51.145 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db                   | 2025-08-01 11:05:51.203 UTC [66] LOG:  database system was shut down at 2025-08-01 11:05:51 UTC
db                   | 2025-08-01 11:05:51.207 UTC [1] LOG:  database system is ready to accept connections
api2-1               | Connected to Redis
api2-1               | 2025/08/01 11:05:52 Servidor iniciado na porta :8080
api1-1               | Connected to Redis
api1-1               | 2025/08/01 11:05:52 Servidor iniciado na porta :8080
nginx_load_balancer  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_load_balancer  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_load_balancer  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_load_balancer  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx_load_balancer  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx_load_balancer  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx_load_balancer  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_load_balancer  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_load_balancer  | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_load_balancer  | 2025/08/01 11:05:56 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.20.0.5:8080/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 2025/08/01 11:05:56 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.20.0.4:8080/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 172.20.0.1 - - [01/Aug/2025:11:05:56 +0000] "GET /payments-summary HTTP/1.1" 502 157 "-" "curl/7.88.1"
nginx_load_balancer  | 172.20.0.1 - - [01/Aug/2025:11:06:01 +0000] "GET /payments-summary HTTP/1.1" 502 157 "-" "curl/7.88.1"
nginx_load_balancer  | 2025/08/01 11:06:01 [error] 30#30: *4 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api_servers/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 172.20.0.1 - - [01/Aug/2025:11:06:06 +0000] "GET /payments-summary HTTP/1.1" 502 157 "-" "curl/7.88.1"
nginx_load_balancer  | 2025/08/01 11:06:06 [error] 30#30: *5 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api_servers/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 2025/08/01 11:06:11 [error] 30#30: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.20.0.4:8080/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 2025/08/01 11:06:11 [error] 30#30: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.20.0.5:8080/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 172.20.0.1 - - [01/Aug/2025:11:06:11 +0000] "GET /payments-summary HTTP/1.1" 502 157 "-" "curl/7.88.1"
nginx_load_balancer  | 2025/08/01 11:06:16 [error] 30#30: *9 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api_servers/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 172.20.0.1 - - [01/Aug/2025:11:06:16 +0000] "GET /payments-summary HTTP/1.1" 502 157 "-" "curl/7.88.1"
nginx_load_balancer  | 2025/08/01 11:06:21 [error] 30#30: *10 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api_servers/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 172.20.0.1 - - [01/Aug/2025:11:06:21 +0000] "GET /payments-summary HTTP/1.1" 502 157 "-" "curl/7.88.1"
nginx_load_balancer  | 2025/08/01 11:06:26 [error] 30#30: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.20.0.4:8080/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 2025/08/01 11:06:26 [error] 30#30: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.20.0.5:8080/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 172.20.0.1 - - [01/Aug/2025:11:06:26 +0000] "GET /payments-summary HTTP/1.1" 502 157 "-" "curl/7.88.1"
nginx_load_balancer  | 172.20.0.1 - - [01/Aug/2025:11:06:31 +0000] "GET /payments-summary HTTP/1.1" 502 157 "-" "curl/7.88.1"
nginx_load_balancer  | 2025/08/01 11:06:31 [error] 30#30: *14 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api_servers/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 172.20.0.1 - - [01/Aug/2025:11:06:36 +0000] "GET /payments-summary HTTP/1.1" 502 157 "-" "curl/7.88.1"
nginx_load_balancer  | 2025/08/01 11:06:36 [error] 30#30: *15 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api_servers/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 2025/08/01 11:06:41 [error] 30#30: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.20.0.4:8080/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 2025/08/01 11:06:41 [error] 30#30: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.20.0.5:8080/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 172.20.0.1 - - [01/Aug/2025:11:06:41 +0000] "GET /payments-summary HTTP/1.1" 502 157 "-" "curl/7.88.1"
nginx_load_balancer  | 2025/08/01 11:06:46 [error] 30#30: *19 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api_servers/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 172.20.0.1 - - [01/Aug/2025:11:06:46 +0000] "GET /payments-summary HTTP/1.1" 502 157 "-" "curl/7.88.1"
nginx_load_balancer  | 2025/08/01 11:06:51 [error] 30#30: *20 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api_servers/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 172.20.0.1 - - [01/Aug/2025:11:06:51 +0000] "GET /payments-summary HTTP/1.1" 502 157 "-" "curl/7.88.1"
nginx_load_balancer  | 2025/08/01 11:06:56 [error] 30#30: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.20.0.4:8080/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 2025/08/01 11:06:56 [error] 30#30: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.20.0.5:8080/payments-summary", host: "localhost:9999"
nginx_load_balancer  | 172.20.0.1 - - [01/Aug/2025:11:06:56 +0000] "GET /payments-summary HTTP/1.1" 502 157 "-" "curl/7.88.1"
[Knginx_load_balancer exited with code 0
[Kapi2-1 exited with code 2
[Kapi1-1 exited with code 2
db                   | 2025-08-01 11:07:02.575 UTC [1] LOG:  received fast shutdown request
db                   | 2025-08-01 11:07:02.575 UTC [1] LOG:  aborting any active transactions
redis                | 1:signal-handler (1754046422) Received SIGTERM scheduling shutdown...
db                   | 2025-08-01 11:07:02.581 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db                   | 2025-08-01 11:07:02.581 UTC [64] LOG:  shutting down
db                   | 2025-08-01 11:07:02.581 UTC [64] LOG:  checkpoint starting: shutdown immediate
db                   | 2025-08-01 11:07:02.582 UTC [64] LOG:  checkpoint complete: wrote 37 buffers (0.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.002 s; sync files=0, longest=0.000 s, average=0.000 s; distance=151 kB, estimate=151 kB
db                   | 2025-08-01 11:07:02.589 UTC [1] LOG:  database system is shut down
redis                | 1:M 01 Aug 2025 11:07:02.636 * User requested shutdown...
redis                | 1:M 01 Aug 2025 11:07:02.636 * Saving the final RDB snapshot before exiting.
redis                | 1:M 01 Aug 2025 11:07:02.655 * DB saved on disk
redis                | 1:M 01 Aug 2025 11:07:02.656 # Redis is now ready to exit, bye bye...
[Kdb exited with code 0
[Kredis exited with code 0
